def Reset_Values(Transcript_ID, Chr, Start, End, Strand, Gene_ID, Gene_Symbol, HGNC_Symbol, Description, Sequence):
    Temp_Transcript_ID  = ''
    Temp_Chr = ''
    Temp_Gene_Start_Coord = ''
    Temp_Gene_End_Coord = ''
    Temp_Gene_Strand = ''
    Temp_Gene_ID = ''
    Temp_Gene_Symbol = ''
    Temp_HGNC_Symbol = ''
    Temp_Gene_Description = ''
    Temp_Sequence = ''
    return()    

Temp_Transcript_ID  = 'aergaerg'
Temp_Chr = 'aer'
Temp_Gene_Start_Coord = 'aer'
Temp_Gene_End_Coord = 'aer'
Temp_Gene_Strand = 'aeraer'
Temp_Gene_ID = 'aer'
Temp_Gene_Symbol = 'aer'
Temp_HGNC_Symbol = 'aer'
Temp_Gene_Description = 'aer'
Temp_Sequence = 'aer'

Reset_Values(Temp_Transcript_ID, Temp_Chr, Temp_Gene_Start_Coord, Temp_Gene_End_Coord, Temp_Gene_Strand, Temp_Gene_ID, Temp_Gene_Symbol, Temp_HGNC_Symbol,Temp_Gene_Description, Temp_Sequence)

print(Temp_Transcript_ID,
Temp_Chr,
Temp_Gene_Start_Coord,
Temp_Gene_End_Coord,
Temp_Gene_Strand,
Temp_Gene_ID,
Temp_Gene_Symbol,
Temp_HGNC_Symbol,
Temp_Gene_Description,
Temp_Sequence)